default:
  level_descr:
    优秀: 请在以后的学习与生活中继续保持，稳固地提高自己的{ab_name}。
    中等: 请在以后继续坚持训练，逐步提升自己的{ab_name}。
    待提高: 该能力还需要重点训练，请结合大脑课堂中的训练方法，坚持每周完成训练，逐步提升自己的{ab_name}。
  item_info:
    item:
      - 位置记忆
      - 顺背数
      - 倒背数
      - 数字魔法师中级
      - 速算师
      - 数字大小比较
      - 数感
      - 蝴蝶照相机
      - 森林萤火虫
      - 二维心理旋转测试
    ab_name:
      - 空间短时记忆
      - 言语短时记忆
      - 言语工作记忆
      - 信息更新能力
      - 数学算术能力
      - 数字加工能力
      - 数量感知能力
      - 空间工作记忆
      - 注意力
      - 数学几何能力
    descr: "{item}主要测量的是{ab_name}。在前测中，该学生的{ab_name}分数为{score_pretest}，在群体中位于{percent_pretest}的位置，评定等级为{level_pretest}；经过一段时间的训练，在第2次的测试中，该学生的{ab_name}分数为{score_posttest}，在群体中位于{percent_posttest}的位置，评定等级为{level_posttest}，上升{percent_up}。"
